import bcrypt from 'bcryptjs';

const data = {
  users : [
    {
      name: 'Rasel Rana',
      email: 'mozahid32@gmail.com',
      password: bcrypt.hashSync('Rasel123'),
      isAdmin: true,
    },
    {
      name: 'Mozahid Rana',
      email: 'mozahid@gmail.com',
      password: bcrypt.hashSync('Rasel123'),
      isAdmin: false,
    },

  ],
  products: [
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-casual-shirt',
      category: 'Shirts',
      image: '/images/shirt1.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-shirt2',
      category: 'Shirts',
      image: '/images/shirt2.png',
      price: 180,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-formal-shirt',
      category: 'Shirts',
      image: '/images/shirt3.png',
      price: 150,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Shirt',
      slug: 'mens-slim-shirt2',
      category: 'Shirts',
      image: '/images/shirt4.png',
      price: 90,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 30,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Skinny Chinos',
      slug: 'chinos-slimfit',
      category: 'Pant',
      image: '/images/pant1.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Skinny Chinos for men, comfortable to wear all seasons',
    },
    {
      name: 'Nicol Skinny Chinos',
      slug: 'nicol-skinny-chinos',
      category: 'Pant',
      image: '/images/pant2.png',
      price: 100,
      brand: 'YD',
      rating: 4.8,
      numReviews: 25,
      countInStock: 30,
      description: 'Nicol Skinny Chinos for men, comfortable to wear all seasons',
    },
    {
      name: 'Danny Super Stretch Slim Chinos',
      slug: 'danny-slim-chinos',
      category: 'Pant',
      image: '/images/pant3.png',
      price: 100,
      brand: 'YD',
      rating: 4.5,
      numReviews: 58,
      countInStock: 65,
      description: 'Danny Super Stretch Slim Chinos, comfortable to wear all seasons',
    },
    {
      name: 'Nicol Skinny Chinos',
      slug: 'mens-nicol-skinny-chinos2',
      category: 'Pant',
      image: '/images/pant4.png',
      price: 100,
      brand: 'YD',
      rating: 4.8,
      numReviews: 48,
      countInStock: 74,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Garbo Leather Dress Shoe',
      slug: 'garbo-leather-shoes',
      category: 'Shoes',
      image: '/images/dressShoes.png',
      price: 180,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Leather shoes for men, comfortable to wear all seasons',
    },
    {
      name: 'Mercury Leather Dress Shoe',
      slug: 'mercury-leather-shoes',
      category: 'Shoes',
      image: '/images/dressShoes2.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Mercury leather shoes for men, comfortable to wear all seasons',
    },
    {
      name: 'Chase Stretch Blazer',
      slug: 'chase-stretch-blazer',
      category: 'Suits',
      image: '/images/blazer.png',
      price: 200,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
      description: 'Casual Blazer for men, comfortable to wear all seasons',
    },
  ],
};

export default data;
