import bcrypt from 'bcryptjs';

const data = {
  users : [
    {
      name: 'Rasel Rana',
      email: 'mozahid32@gmail.com',
      password: bcrypt.hashSync('Rasel123'),
      isAdmin: true,
    },
    {
      name: 'Mozahid Rana',
      email: 'mozahid@gmail.com',
      password: bcrypt.hashSync('Rasel123'),
      isAdmin: false,
    },

  ],
  products: [
    {
      name: 'PACO RABANNE 1 MILLION EAU DE TOILETTE 100ML',
      slug: 'paco-rabanne-1-million-100ml',
      category: 'Perfume',
      image: '/images/paco.jpg',
      price: 142,
      brand: 'Paco Rabannne',
      rating: 4.5,
      numReviews: 500,
      countInStock: 15,
      description: 'Going for gold because decadence is thrilling. Not-so-gentle man. Elegant and impertinent in equal measure, an intoxicating, powerful blend that starts out fresh and moves onto a spicy leather accord.',
    },
    {
      name: 'EROS FLAME EDP 100ML SET',
      slug: 'eros-flame-set',
      category: 'Perfume',
      image: '/images/versace.jpg',
      price: 155,
      brand: 'Versace',
      rating: 4.5,
      numReviews: 900,
      countInStock: 12,
      description: 'Set contains: Versace Eros Pour Homme Flame EDP 100ml + Deodorant Stick 75ml + Travel Spray 10ml Inspired by Eros, God of Love, who was able to make people fall in love with his bow and arrow, Versace Eros Flame eau de parfum is an oriental and woody awakening for men.',
    },
    {
      name: 'BLEU DE CHANEL Eau de Parfum Spray 150ml',
      slug: 'bleu-de-chanel-150ml',
      category: 'Perfume',
      image: '/images/chanel.jpg',
      price: 215,
      brand: 'Versace',
      rating: 4.9,
      numReviews: 100,
      countInStock: 10,
      description: 'A tribute to masculine freedom in an aromatic-woody fragrance with a captivating trail. A timeless, powerful fragrance housed in an enigmatic blue bottle. The uncompromising spirit of BLEU DE CHANEL conveyed in an Eau de Parfum for men. ',
    },
    {
      name: 'MENS BLACK WATCH',
      slug: 'mens-black-watch',
      category: 'Watch',
      image: '/images/armani1.jpg',
      price: 879,
      brand: 'Emporio Armani',
      rating: 4.9,
      numReviews: 15,
      countInStock: 10,
      description: 'This stylish mens watch from Emporio Armani features a matte black IP case, matte black skeleton dial with a pop of black IP plating on the inner movement and black rubarized leather strap',
    },
    {
      name: 'PHYLIPA TAN LEATHER WATCH',
      slug: 'phylipa-tans-watch',
      category: 'Watch',
      image: '/images/tedbaker.jpg',
      price: 260,
      brand: 'TED BAKER',
      rating: 4.4,
      numReviews: 20,
      countInStock: 10,
      description: 'This stylish mens watch from Emporio Armani features a matte black IP case, matte black skeleton dial with a pop of black IP plating on the inner movement and black rubarized leather strap',
    },
    {
      name: 'WAYFARER SQUARE BLACK GREEN ACETATE SUNGLASSES',
      slug: 'wayfarer-square-black-rayban',
      category: 'Sunglass',
      image: '/images/payban.jpg',
      price: 240,
      brand: 'RAY BAN',
      rating: 4.6,
      numReviews: 150,
      countInStock: 10,
      description: 'Ray Ban SunglassesWayfarer Black Crystal GreenSquareUV Category 3Non Polar',
    },
    {
      name: 'Rob Irregular Gold Green Metal Sunglass',
      slug: 'rob-gold-green-metal',
      category: 'Sunglass',
      image: '/images/rayban1.jpg',
      price: 208,
      brand: 'RAY BAN',
      rating: 4.6,
      numReviews: 57,
      countInStock: 15,
      description: 'Ray Ban SunglassRob Arista Crystal GreenIrregularUV Category 3Non Polar',
    },
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-casual-shirt',
      category: 'Shirts',
      image: '/images/shirt1.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-shirt2',
      category: 'Shirts',
      image: '/images/shirt2.png',
      price: 180,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Casual Shirt',
      slug: 'mens-formal-shirt',
      category: 'Shirts',
      image: '/images/shirt3.png',
      price: 150,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Shirt',
      slug: 'mens-slim-shirt2',
      category: 'Shirts',
      image: '/images/shirt4.png',
      price: 90,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 30,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Mens Skinny Chinos',
      slug: 'chinos-slimfit',
      category: 'Pant',
      image: '/images/pant1.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Skinny Chinos for men, comfortable to wear all seasons',
    },
    {
      name: 'Nicol Skinny Chinos',
      slug: 'nicol-skinny-chinos',
      category: 'Pant',
      image: '/images/pant2.png',
      price: 100,
      brand: 'YD',
      rating: 4.8,
      numReviews: 25,
      countInStock: 30,
      description: 'Nicol Skinny Chinos for men, comfortable to wear all seasons',
    },
    {
      name: 'Danny Super Stretch Slim Chinos',
      slug: 'danny-slim-chinos',
      category: 'Pant',
      image: '/images/pant3.png',
      price: 100,
      brand: 'YD',
      rating: 4.5,
      numReviews: 58,
      countInStock: 65,
      description: 'Danny Super Stretch Slim Chinos, comfortable to wear all seasons',
    },
    {
      name: 'Nicol Skinny Chinos',
      slug: 'mens-nicol-skinny-chinos2',
      category: 'Pant',
      image: '/images/pant4.png',
      price: 100,
      brand: 'YD',
      rating: 4.8,
      numReviews: 48,
      countInStock: 74,
      description: 'Slim fit shirt for men, comfortable to wear all seasons',
    },
    {
      name: 'Garbo Leather Dress Shoe',
      slug: 'garbo-leather-shoes',
      category: 'Shoes',
      image: '/images/dressShoes.png',
      price: 180,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Leather shoes for men, comfortable to wear all seasons',
    },
    {
      name: 'Mercury Leather Dress Shoe',
      slug: 'mercury-leather-shoes',
      category: 'Shoes',
      image: '/images/dressShoes2.png',
      price: 80,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 24,
      description: 'Mercury leather shoes for men, comfortable to wear all seasons',
    },
    {
      name: 'Chase Stretch Blazer',
      slug: 'chase-stretch-blazer',
      category: 'Suits',
      image: '/images/blazer.png',
      price: 200,
      brand: 'YD',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
      description: 'Casual Blazer for men, comfortable to wear all seasons',
    },
  ],
};

export default data;
